# site settings
title: Mayavi's Blog
subtitle: Art &#8226; Design &#8226; Engineering
email: maya.mahesh2020@gmail.com
description: Art, Design, and Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mayavink.com" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: India
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/mayavink
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown
permalink: /:title/

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
